apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apd.fullname" . }}
  labels:
    {{- include "apd.labels" . | nindent 4 }}
data:
  apd.json: |-
    {{- include "apd.configJson" . | nindent 4 }}
