{{- /* Signing keys: create a Secret only when keysJson is provided inline and
       no existingSecret is referenced. */ -}}
{{- if and (not .Values.keys.existingSecret) .Values.keys.keysJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-keys" (include "apd.fullname" .) }}
  labels:
    {{- include "apd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.keys.existingSecretKey }}: |-
    {{- .Values.keys.keysJson | nindent 4 }}
{{- end }}
{{- if and .Values.admin.enabled (not .Values.admin.existingSecret) .Values.admin.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin" (include "apd.fullname" .) }}
  labels:
    {{- include "apd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.admin.existingSecretKey }}: {{ .Values.admin.value | quote }}
{{- end }}
{{- if and (not .Values.staticEnrollToken.existingSecret) .Values.staticEnrollToken.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-static-enroll" (include "apd.fullname" .) }}
  labels:
    {{- include "apd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.staticEnrollToken.existingSecretKey }}: {{ .Values.staticEnrollToken.value | quote }}
{{- end }}
